//Debug box
KV.debug = function(params){
  let dombox = document.getElementById("kvdebug");
  if (!dombox){
    dombox = document.createElement("DIV");
    dombox.id = "kvdebug";
    dombox.style = "position: fixed; bottom: 2vh; right: 2vw; width: 80vw; height: 10vh; border: 2px solid green; background: rgba(0,0,0,0.5); color: green; font-family: monospace; z-index:99999999; overflow: auto;";    document.getElementsByTagName("body")[0].appendChild(dombox);
  }
  let debuginfo = document.createElement("DIV");
  debuginfo.style = "border-bottom: 1px dashed lime-green;"
  debuginfo.innerHTML = typeof params == "string" ? params : JSON.stringify(params);
  dombox.appendChild(debuginfo);
  dombox.scrollTop = dombox.scrollHeight;
}
//NOTE: The "chain" variable is declared here. Feel free to move it if you need to adjust the scope 
let chain={read:{},write:{},pay:{}};
//Declare the wallet_address variable to store the reference to the currently connected wallet
let user_wallet;
chain["read"]["JedstarStaking"] = {};chain["write"]["JedstarStaking"] = {};chain["pay"]["JedstarStaking"] = {};
chain["read"]["JedstarStakingRO"] = {};chain["read"]["JEDToken"] = {};chain["write"]["JEDToken"] = {};chain["pay"]["JEDToken"] = {};

let walletui;

/** ATTENTION: You should customise this function to match your site requirements.
 * This is where all the action happens. This method is fired once all the web3
 * libraries are loaded and the DOM is ready to be hooked into.
 **/
let init_all = function(res){
  //For a full list of all WalletUIHandler hooks, events, and examples, visit https://www.github.com/kaiesh/connect-web3-wallets
  //Initialise the Wallet UI manager
  walletui = new KV.WalletUIHandler({
    //UPDATE THESE REFERENCES FOR YOUR DOM
    parent_container: document.getElementById("walletmodal"),
    btn_connect: document.getElementById("connect_btn"),
    btn_disconnect_label: "<div><img src='/img/agora/wallet.svg'> <span id='walletaddr'>Disconnect</span>",
    web3network: 80001,
    //ADD ADDITIONAL WALLETUI PROPS HERE
  });

  walletui.on("modal_open", function(msg){
    //add ML to achieve styling goals
    walletBtns = document.getElementsByClassName("kvwalletbtn");
    for (let i = 0; i < walletBtns.length; i++){
      if (walletBtns[i].innerHTML == "Binance"){
        walletBtns[i].innerHTML = "<div class='inner'><div class='wallet-name'>"+walletBtns[i].innerHTML+"</div><div class='wallet-icon'><img src='/img/agora/"+ walletBtns[i].innerHTML +".svg'></div></div>";
      }
      walletBtns[i].innerHTML = "<div class='inner'><div class='wallet-name'>"+walletBtns[i].innerHTML+"</div><div class='wallet-icon'><img src='/img/agora/"+ walletBtns[i].innerHTML +".png'></div></div>";
      }
      document.querySelector(".kvwalletmodal h2").insertAdjacentHTML("afterend", "<div class='rainbow-border'></div>");
  });
  //Contracts with write requirements will be created once a wallet is connected
  walletui.on("wallet_connected", function(wallet_addr){
    //store the address of the connected wallet
    /*check if wallet_addr is an array (check for length as well)*/
    user_wallet = wallet_addr[0];

    let dombody = document.getElementsByTagName("body")[0];
    dombody.classList.add("connected");
    if (dombody.classList.contains("modal-yourwallet")){
      dombody.classList.remove("modalOpen");
      dombody.classList.remove("modal-yourwallet");
    }
    document.getElementById('walletaddr').innerHTML = user_wallet.substr(0,5)+"..."+user_wallet.substr(-4);
    //load all RW contracts
    KV.ContractFns.prepare_contract({short_name: 'JedstarStaking',contract_address:'0x7d2A8685597D04bD5D42fcE2d25B31d86E420501',contract_abi:'/abi/staking-abi.json'}).then(function(res){ console.log('Loaded contract JedstarStaking'); });

    KV.ContractFns.prepare_contract({short_name: 'JEDToken',contract_address:'0xbA89B86C23b7Bb0BA403178354f6B86EeA9EaDf2',contract_abi:'/abi/jedtoken-abi.json'}).then(function(res){ 
      console.log('Loaded contract JEDToken'); 
    });

    //NOTE: ADD ALL ACTIONS THAT SHOULD BE CARRIED OUT HERE ONCE THE WALLET IS CONNECTED
    // --- your code after wallet init goes here ---
  });
  //Web3 handlers are available, so initialise all read-only contracts
  KV.ContractFns.prepare_contract({short_name: 'JedstarStakingRO',contract_address:'0x7d2A8685597D04bD5D42fcE2d25B31d86E420501',contract_abi:'/abi/staking-abi.json',readonly_from_chain_id: 80001}).then(function(res){ 
    console.log('Loaded contract JedstarStakingRO'); 
  });
  shield('/js/starstaking.js', null, 'head', 'script', 0);
  // enable login button
  let loginBtn = document.getElementById("connect_btn");
  let loginP = document.querySelector("#connect_btn span");
  if (loginBtn && loginP){
      loginBtn.disabled = false;
      loginP.innerHTML = "Log In"; 
  }else{
    console.error("Login button not as expected", loginBtn, loginP);
  }
}
/** End of init block **/
//prepare the procedure that will ready all web3 mgmt once the interface libraries are loaded
let web3_init_fn = function(){
  //set Infura API key
   KV.set_infuraID('a869ff8a02834a1dbc4614a626dba74f');
  //Retrieve and initialise the remaining Web3 libraries to support wallet connectivity
  //upon completion, launch the fn that will bind to the DOM and hook into wallet events
  KV.init(["https://cdn.kaiesh.com/js/KV.WalletUIHandler.latest.min.js", "https://cdn.kaiesh.com/js/KV.ContractFns.latest.min.js"]).then(init_all);
}
//Define all the JS handlers to communicate with the web3 contract
chain["read"]["JedstarStaking"]["addressMap1"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressMap1(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["addressMap2"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressMap2(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["addressMap3"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressMap3(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["addressStore1"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressStore1(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["addressStore2"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressStore2(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["addressStore3"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.addressStore3(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["dailyInterestRate1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["dailyInterestRate2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["dailyInterestRate3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn1"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn1(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn2"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn2(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn3"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn3(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["maxStakeAmt1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["maxStakeAmt2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["maxStakeAmt3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakeAmt1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakeAmt2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakeAmt3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakePeriod1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakePeriod2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["minStakePeriod3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["numberOfAddressesCurrentlyStaked1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["numberOfAddressesCurrentlyStaked2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["numberOfAddressesCurrentlyStaked3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["rewardToken"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.rewardToken().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["stakingToken"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.stakingToken().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalAccumulatedInterest1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalAccumulatedInterest2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalAccumulatedInterest3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakeable1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakeable1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakeable2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakeable2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakeable3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakeable3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStaked1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStaked1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStaked2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStaked2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStaked3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStaked3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakedAmount1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakedAmount2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalStakedAmount3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalWithdrawals1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalWithdrawals2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStaking"]["totalWithdrawals3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals3().call().then(resolve).catch(reject);})});}

chain["write"]["JedstarStaking"]["changeOwner"] = function(_newOwner,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeOwner(_newOwner).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_maxStakeAmt1"] = function(_maxStakeAmt1,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_maxStakeAmt1(_maxStakeAmt1).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_maxStakeAmt2"] = function(_maxStakeAmt2,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_maxStakeAmt2(_maxStakeAmt2).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_maxStakeAmt3"] = function(_maxStakeAmt3,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_maxStakeAmt3(_maxStakeAmt3).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakeAmt1"] = function(_minStakeAmt1,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakeAmt1(_minStakeAmt1).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakeAmt2"] = function(_minStakeAmt2,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakeAmt2(_minStakeAmt2).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakeAmt3"] = function(_minStakeAmt3,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakeAmt3(_minStakeAmt3).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakePeriod1"] = function(_minStakePeriod1,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakePeriod1(_minStakePeriod1).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakePeriod2"] = function(_minStakePeriod2,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakePeriod2(_minStakePeriod2).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_minStakePeriod3"] = function(_minStakePeriod3,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_minStakePeriod3(_minStakePeriod3).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_totalStakeable1"] = function(_totalValue,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_totalStakeable1(_totalValue).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_totalStakeable2"] = function(_totalValue,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_totalStakeable2(_totalValue).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["changeValueOf_totalStakeable3"] = function(_totalValue,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.changeValueOf_totalStakeable3(_totalValue).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["modifyDailyInterestRate1"] = function(_dailyInterestRate,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.modifyDailyInterestRate1(_dailyInterestRate).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["modifyDailyInterestRate2"] = function(_dailyInterestRate,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.modifyDailyInterestRate2(_dailyInterestRate).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["modifyDailyInterestRate3"] = function(_dailyInterestRate,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.modifyDailyInterestRate3(_dailyInterestRate).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["stake1"] = function(_stakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.stake1(_stakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["stake2"] = function(_stakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.stake2(_stakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["stake3"] = function(_stakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.stake3(_stakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["unstake1"] = function(_unstakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.unstake1(_unstakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["unstake2"] = function(_unstakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.unstake2(_unstakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["unstake3"] = function(_unstakeAmt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.unstake3(_unstakeAmt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JedstarStaking"]["withdrawToken"] = function(_amt,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStaking').then(function(w3ct){w3ct.w3contract.methods.withdrawToken(_amt).send({from: user_wallet, to: '0x52b7c56C2e34A2e6fE343F15a8d233511088C27F', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}

chain["read"]["JedstarStakingRO"]["addressMap1"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressMap1(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["addressMap2"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressMap2(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["addressMap3"] = function(address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressMap3(address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["addressStore1"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressStore1(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["addressStore2"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressStore2(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["addressStore3"] = function(uint256){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.addressStore3(uint256).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["dailyInterestRate1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["dailyInterestRate2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["dailyInterestRate3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.dailyInterestRate3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn1"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn1(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn2"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn2(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn3"] = function(_address){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.interestEarnedUpToNowBeforeTaxesAndNotYetWithdrawn3(_address).call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["maxStakeAmt1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["maxStakeAmt2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["maxStakeAmt3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.maxStakeAmt3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakeAmt1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakeAmt2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakeAmt3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakeAmt3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakePeriod1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakePeriod2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["minStakePeriod3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.minStakePeriod3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["numberOfAddressesCurrentlyStaked1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["numberOfAddressesCurrentlyStaked2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["numberOfAddressesCurrentlyStaked3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.numberOfAddressesCurrentlyStaked3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["rewardToken"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.rewardToken().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["stakingToken"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.stakingToken().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalAccumulatedInterest1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalAccumulatedInterest2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalAccumulatedInterest3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalAccumulatedInterest3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakeable1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakeable1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakeable2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakeable2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakeable3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakeable3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStaked1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStaked1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStaked2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStaked2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStaked3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStaked3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakedAmount1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakedAmount2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalStakedAmount3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalStakedAmount3().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalWithdrawals1"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals1().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalWithdrawals2"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals2().call().then(resolve).catch(reject);})});}
chain["read"]["JedstarStakingRO"]["totalWithdrawals3"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JedstarStakingRO').then(function(w3ct){w3ct.w3contract.methods.totalWithdrawals3().call().then(resolve).catch(reject);})});}

chain["read"]["JEDToken"]["DEFAULT_ADMIN_ROLE"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.DEFAULT_ADMIN_ROLE().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["DOMAIN_SEPARATOR"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.DOMAIN_SEPARATOR().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["MARKETING_WALLET"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.MARKETING_WALLET().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["MINTER_ROLE"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.MINTER_ROLE().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["PAUSER_ROLE"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.PAUSER_ROLE().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["TAXMAN_ROLE"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.TAXMAN_ROLE().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["TAX_BURN"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.TAX_BURN().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["TAX_MARKETING"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.TAX_MARKETING().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["TOKENS_MAX_MINT"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.TOKENS_MAX_MINT().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["TOKENS_MINTED"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.TOKENS_MINTED().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["UPGRADER_ROLE"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.UPGRADER_ROLE().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["allowance"] = function(owner,spender){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.allowance(owner,spender).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["balanceOf"] = function(account){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.balanceOf(account).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["decimals"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.decimals().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["getRoleAdmin"] = function(role){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.getRoleAdmin(role).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["hasRole"] = function(role,account){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.hasRole(role,account).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["isTokenLaunched"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.isTokenLaunched().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["is_frozen"] = function(_addr){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.is_frozen(_addr).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["name"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.name().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["nonces"] = function(owner){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.nonces(owner).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["paused"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.paused().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["proxiableUUID"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.proxiableUUID().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["supportsInterface"] = function(interfaceId){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.supportsInterface(interfaceId).call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["symbol"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.symbol().call().then(resolve).catch(reject);})});}
chain["read"]["JEDToken"]["totalSupply"] = function(){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.totalSupply().call().then(resolve).catch(reject);})});}

/* spender = contract addr, amount sum of maxStaking amount */
chain["write"]["JEDToken"]["approve"] = function(spender,amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.approve(spender,amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["asset_freeze"] = function(_addr,_isFrozen,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.asset_freeze(_addr,_isFrozen).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["burn"] = function(amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.burn(amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["burnFrom"] = function(account,amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.burnFrom(account,amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["change_marketing_wallet"] = function(_new_wallet,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.change_marketing_wallet(_new_wallet).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["change_tax"] = function(_burn,_marketing,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.change_tax(_burn,_marketing).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["decreaseAllowance"] = function(spender,subtractedValue,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.decreaseAllowance(spender,subtractedValue).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["grantRole"] = function(role,account,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.grantRole(role,account).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["increaseAllowance"] = function(spender,addedValue,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.increaseAllowance(spender,addedValue).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["initialize"] = function(tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.initialize().send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["mint"] = function(to,amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.mint(to,amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["pause"] = function(tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.pause().send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["permit"] = function(owner,spender,value,deadline,v,r,s,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.permit(owner,spender,value,deadline,v,r,s).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["renounceRole"] = function(role,account,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.renounceRole(role,account).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["revokeRole"] = function(role,account,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.revokeRole(role,account).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["setTokenLaunched"] = function(_isLaunched,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.setTokenLaunched(_isLaunched).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["set_taxfree"] = function(_recipient,_untaxed,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.set_taxfree(_recipient,_untaxed).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["transfer"] = function(recipient,_amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.transfer(recipient,_amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["transferFrom"] = function(from,to,amount,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.transferFrom(from,to,amount).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["unpause"] = function(tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.unpause().send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}
chain["write"]["JEDToken"]["upgradeTo"] = function(newImplementation,tx_update_fn){ return new Promise((resolve, reject) => { KV.ContractFns.when_ready('JEDToken').then(function(w3ct){w3ct.w3contract.methods.upgradeTo(newImplementation).send({from: user_wallet, to: '0xF6D0762C645E873E5884E69BBcB2F074E6067A70', value:0}, function(err,tx){if (typeof tx_update_fn == 'function'){ tx_update_fn(tx, err); }}).then(function(res){resolve(res);}).catch(function(erx){reject(erx);});})});}


//Define some necessary functions for operations
var ajax = function(e,r){var t="";for(var n in e)e.hasOwnProperty(n)&&(t+=(""==t?"":"&")+n+"="+encodeURIComponent(e[n]));var o={api_url:"/api/",request_header:"application/x-www-form-urlencoded",json_return:!0,method:"POST"};if("object"==typeof r)for(n in r)r.hasOwnProperty(n)&&(o[n]=r[n]);return new Promise(((e,r)=>{var n=new XMLHttpRequest;n.open(o.method,o.api_url),n.setRequestHeader("Content-Type",o.request_header),n.onload=function(){if(200===n.status){var t=o.json_return?JSON.parse(n.responseText):n.responseText;e(t)}else r({status:"fail",resp:t})},n.send(t)}))};var shield = function ( s, h, i, e, l, d ){ var g = document.createElement(e); g.src = s; if (typeof h=="function") g.onload=h; g.async="async"; document.getElementsByTagName(i)[l].appendChild(g);};

//With all definitions in place, pull the primary web3 library down and kick-start everything

shield("https://cdn.kaiesh.com/js/KV.latest.min.js", web3_init_fn, "head", "script", 0);